# Generated by Django 5.2.7 on 2025-11-19 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_manager', models.CharField(blank=True, max_length=100, null=True)),
                ('keyskills', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_profiles',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Technical Training', 'Technical Training'), ('Employee Wellbeing', 'Employee Wellbeing'), ('Leadership Development', 'Leadership Development'), ('Compliance', 'Compliance'), ('General', 'General')], default='General', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='draft', max_length=20)),
                ('creation_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('ai_content', models.JSONField(blank=True, null=True)),
                ('ai_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('quiz', models.JSONField(blank=True, null=True)),
                ('assessment_info', models.JSONField(blank=True, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('scheduled_datetime', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('certification', models.JSONField(blank=True, null=True)),
                ('has_certificate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.JSONField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_sessions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='authentication.session')),
            ],
            options={
                'db_table': 'session_completions',
                'unique_together': {('employee', 'session')},
            },
        ),
        migrations.CreateModel(
            name='SessionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts_used', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('locked_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_requests', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.session')),
            ],
            options={
                'db_table': 'session_requests',
                'unique_together': {('employee', 'session')},
            },
        ),
    ]
