# Generated by Django 5.2.7 on 2025-11-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employeeprofile_session_sessioncompletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
