# Generated by Django 5.2.7 on 2025-11-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_password_reset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
