# Generated by Django 5.2.7 on 2026-01-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_session_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
