# Generated by Django 5.2.7 on 2026-01-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_session_audience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessioncompletion',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='sessioncompletion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessioncompletion',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessioncompletion',
            name='attempt_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sessioncompletion',
            unique_together={('employee', 'session', 'attempt_number')},
        ),
    ]
