# Generated by Django 6.0 on 2026-01-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('session_approved', 'Session Approved'), ('session_rejected', 'Session Rejected'), ('session_completed', 'Session Completed'), ('certificate_earned', 'Certificate Earned'), ('session_scheduled', 'Session Scheduled'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
